describe('Тестирование виртуальной клавиатуры', () => {
    
    it('Отображение виртуальной клавиатуры', () => {
        cy.visit('https://google.com')        
        cy.get('body > div.L3eUgb > div.o3j99.ikrT4e.om7nvf > form > div:nth-child(1) > div.A8SBwf > div.RNNXgb > div.SDkEP > div.dRYYxd > div.Umvnrc').click()
        cy.get('#kbd').should('be.visible');    
    });

    it('Проверка символов виртуальной клавиатуры русской клавиатуры', () => {
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('ё').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('0').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('1').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('2').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('3').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('4').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('5').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('6').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('7').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('8').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('9').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('-').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(1)').contains('=').click()
        cy.get('#K8').click()        
        cy.get('#kbd > div:nth-child(2) > div:nth-child(2)').contains('й').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(2)').contains('ц').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(2)').contains('у').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(2)').contains('к').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(2)').contains('е').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(2)').contains('н').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(2)').contains('г').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(2)').contains('ш').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(2)').contains('щ').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(2)').contains('з').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(2)').contains('х').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(2)').contains('ъ').click()
        cy.get('#K220').click()
        cy.get('#K8').click()                     
        cy.get('#K20').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(3)').contains('Ф').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(3)').contains('Ы').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(3)').contains('В').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(3)').contains('А').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(3)').contains('П').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(3)').contains('Р').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(3)').contains('О').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(3)').contains('Л').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(3)').contains('Д').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(3)').contains('Ж').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(3)').contains('Э').click()
        cy.get('#K32').click()
        cy.get('#K16').click()        
        cy.get('#kbd > div:nth-child(2) > div:nth-child(4)').contains('я').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(4)').contains('Ч').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(4)').contains('С').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(4)').contains('М').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(4)').contains('И').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(4)').contains('Т').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(4)').contains('Ь').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(4)').contains('Б').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(4)').contains('Ю').click()
        cy.get('#kbd > div:nth-child(2) > div:nth-child(4)').contains('.').click()
        cy.get('.gLFyf').should('have.value', 'ё0123456789-йцукенгшщзхъФЫВАПРОЛДЖЭ яЧСМИТЬБЮ.')
        cy.get('.gLFyf').clear().should('have.value','')
    });
})

describe('Проверка раскладки "Ctrl+Alt" на виртуальной клавиатуре', () => {
    it('Проверка символов раскладки', ()=>{
        cy.get('#K273').click()        
        cy.get('#K192').click()
        cy.get('#K273').click()
        cy.get('#K81').click()
        cy.get('#K273').click()
        cy.get('#K69').click()
        cy.get('#K273').click()
        cy.get('#K82').click()
        cy.get('#K273').click()           
        cy.get('#K84').click()
        cy.get('#K273').click()
        cy.get('#K89').click()
        cy.get('#K273').click()
        cy.get('#K85').click()
        cy.get('#K273').click()
        cy.get('#K73').click()
        cy.get('#K273').click()
        cy.get('#K79').click()
        cy.get('#K273').click()
        cy.get('#K80').click()
        cy.get('#K273').click()
        cy.get('#K219').click()
        cy.get('#K273').click()
        cy.get('#K221').click()
        cy.get('#K273').click()
        cy.get('#K220').click()
        cy.get('#K273').click()
        cy.get('#K65').click()
        cy.get('#K273').click()
        cy.get('#K83').click()
        cy.get('#K273').click()
        cy.get('#K74').click()
        cy.get('#K273').click()
        cy.get('#K75').click()
        cy.get('#K273').click()
        cy.get('#K76').click()
        cy.get('#K273').click()
        cy.get('#K186').click()
        cy.get('#K273').click()
        cy.get('#K90').click()
        cy.get('#K273').click()
        cy.get('#K88').click()
        cy.get('#K273').click()
        cy.get('#K66').click()
        cy.get('#K273').click()
        cy.get('#K78').click()
        cy.get('#K273').click()
        cy.get('#K77').click()
        cy.get('.gLFyf').should('have.value', 'ѢЇѪѬѤЅѮ[]\ѲѰѠѾѺѼѦѨІѴѶ')
    })

describe('Проверка закрытия виртуальной клавиатуре', () => {
    it('Проверка символа закрытия виртуальной клавиатуры', () => {
        cy.get('.vk-t-btn').click().should('not.be.visible')
    })
    
})
})

        
